################################################################################
#   Fichero para montar la estructura docker
################################################################################
version: '2'

networks:
  laliganetwork:

services:
  #Definimos los parametros de cada uno de los contenedores de la red
  #Los contenedores de los peers deberan tener su couchdb
  orderer.laliga.com:
    extends:
      file:   base/docker-compose-base.yaml
      service: orderer.laliga.com
    container_name: orderer.laliga.com
    networks:
      - laliganetwork

  peer0.laliga.org.laliga.com:
    container_name: peer0.laliga.org.laliga.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.laliga.org.laliga.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbliga:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - orderer.laliga.com
      - couchdbliga
    networks:
      - laliganetwork

  peer0.realmadrid.org.laliga.com:
    container_name: peer0.realmadrid.org.laliga.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.realmadrid.org.laliga.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbrma:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - orderer.laliga.com
      - couchdbrma
    networks:
      - laliganetwork

  peer0.barcelona.org.laliga.com:
    container_name: peer0.barcelona.org.laliga.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.barcelona.org.laliga.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbbcn:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - orderer.laliga.com
      - couchdbbcn
    networks:
      - laliganetwork

  peer0.atletico.org.laliga.com:
    container_name: peer0.atletico.org.laliga.com
    extends:
      file:  base/docker-compose-base.yaml
      service: peer0.atletico.org.laliga.com
    environment:
      - CORE_LEDGER_STATE_STATEDATABASE=CouchDB
      - CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS=couchdbatl:5984
      - CORE_LEDGER_STATE_COUCHDBCONFIG_USERNAME=admin
      - CORE_LEDGER_STATE_COUCHDBCONFIG_PASSWORD=adminpw
    depends_on:
      - orderer.laliga.com
      - couchdbatl
    networks:
      - laliganetwork

  #Definimos la CA de la red
  #CA for LaLigaOrg	
  ca.laliga.org.laliga.com:
    image: hyperledger/fabric-ca:1.4.8
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
      - FABRIC_CA_SERVER_CA_NAME=ca.laliga.org.laliga.com
      - FABRIC_CA_SERVER_TLS_ENABLED=true
      - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.laliga.org.laliga-cert.pem
      - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
      - FABRIC_CA_SERVER_CA_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.laliga.org.laliga-cert.pem
      - FABRIC_CA_SERVER_CA_KEYFILE=/etc/hyperledger/fabric-ca-server-config/priv_sk
    ports:
      - "7054:7054"
    command: sh -c 'fabric-ca-server start -b admin:adminpw'
    volumes:
      - ./crypto-config/peerOrganizations/laliga.org.laliga.com/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca.laliga.org.laliga
    networks:
      - laliganetwork
  
  # Habilitamos un cli para gestionar el canal de laliga
  cli-laliga:
    container_name: cli-laliga
    image: hyperledger/fabric-tools:2.2
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.laliga.org.laliga.com:7051
      - CORE_PEER_LOCALMSPID=LaLigaOrgMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/laliga.org.laliga.com/peers/peer0.laliga.org.laliga.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/laliga.org.laliga.com/peers/peer0.laliga.org.laliga.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/laliga.org.laliga.com/peers/peer0.laliga.org.laliga.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/laliga.org.laliga.com/users/Admin@laliga.org.laliga.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/javascript/laliga/:/opt/gopath/src/github.com/chaincode
        - ./scripts/channel-laliga:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.laliga.com
      - peer0.laliga.org.laliga.com
      - peer0.realmadrid.org.laliga.com
      - peer0.barcelona.org.laliga.com
      - peer0.atletico.org.laliga.com
    networks:
      - laliganetwork

  # Habilitamos un cli para gestionar el canal de equipos
  cli-equipos:
    container_name: cli-equipos
    image: hyperledger/fabric-tools:2.2
    tty: true
    stdin_open: true
    environment:
      - GOPATH=/opt/gopath
      - CORE_VM_ENDPOINT=unix:///host/var/run/docker.sock
      - FABRIC_LOGGING_SPEC=DEBUG
      - CORE_PEER_ID=cli
      - CORE_PEER_ADDRESS=peer0.realmadrid.org.laliga.com:7051
      - CORE_PEER_LOCALMSPID=RealMadridOrgMSP
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_CERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/realmadrid.org.laliga.com/peers/peer0.realmadrid.org.laliga.com/tls/server.crt
      - CORE_PEER_TLS_KEY_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/realmadrid.org.laliga.com/peers/peer0.realmadrid.org.laliga.com/tls/server.key
      - CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/realmadrid.org.laliga.com/peers/peer0.realmadrid.org.laliga.com/tls/ca.crt
      - CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/realmadrid.org.laliga.com/users/Admin@realmadrid.org.laliga.com/msp
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/peer
    command: /bin/bash
    volumes:
        - /var/run/:/host/var/run/
        - ./chaincode/javascript/equipos/:/opt/gopath/src/github.com/chaincode
        - ./scripts/channel-equipos:/opt/gopath/src/github.com/hyperledger/fabric/peer/scripts
        - ./crypto-config:/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/
        - ./channel-artifacts:/opt/gopath/src/github.com/hyperledger/fabric/peer/channel-artifacts
    depends_on:
      - orderer.laliga.com
      - peer0.realmadrid.org.laliga.com
      - peer0.barcelona.org.laliga.com
      - peer0.atletico.org.laliga.com
    networks:
      - laliganetwork

  # Configuramos las couchdb
  couchdbliga:
    image: couchdb:3.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports: 
      - 5984:5984
    container_name: couchdbliga
    networks:
      - laliganetwork
  couchdbrma:
    image: couchdb:3.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports: 
      - 5985:5984
    container_name: couchdbrma
    networks:
      - laliganetwork
  couchdbbcn:
    image: couchdb:3.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports: 
      - 5986:5984
    container_name: couchdbbcn
    networks:
      - laliganetwork
  couchdbatl:
    image: couchdb:3.1
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=adminpw
    ports: 
      - 5987:5984
    container_name: couchdbatl
    networks:
      - laliganetwork