cd /opt/gopath/src/github.com/hyperledger/fabric/peer
export CHANNEL_NAME=channel-laliga

# Creamos el canal en base al bloque generado en configall.sh
peer channel create -o orderer.laliga.com:7050 -c $CHANNEL_NAME -f ./channel-artifacts/channel-laliga.tx --tls true --cafile  /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/laliga.com/msp/tlscacerts/tlsca.laliga.com-cert.pem
peer channel join -b channel-laliga.block

# Actualizamos el canal anadiendo cada uno de los peers
CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/realmadrid.org.laliga.com/users/Admin@realmadrid.org.laliga.com/msp CORE_PEER_ADDRESS=peer0.realmadrid.org.laliga.com:7051 CORE_PEER_LOCALMSPID="RealMadridOrgMSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/realmadrid.org.laliga.com/users/Admin@realmadrid.org.laliga.com/tls/ca.crt peer channel join -b channel-laliga.block
CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/barcelona.org.laliga.com/users/Admin@barcelona.org.laliga.com/msp CORE_PEER_ADDRESS=peer0.barcelona.org.laliga.com:7051 CORE_PEER_LOCALMSPID="BarcelonaOrgMSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/barcelona.org.laliga.com/users/Admin@barcelona.org.laliga.com/tls/ca.crt peer channel join -b channel-laliga.block
CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/atletico.org.laliga.com/users/Admin@atletico.org.laliga.com/msp CORE_PEER_ADDRESS=peer0.atletico.org.laliga.com:7051 CORE_PEER_LOCALMSPID="AtleticoOrgMSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/atletico.org.laliga.com/users/Admin@atletico.org.laliga.com/tls/ca.crt peer channel join -b channel-laliga.block
peer channel update -o orderer.laliga.com:7050 -c $CHANNEL_NAME -f ./channel-artifacts/LaLigaOrgMSPanchors-laliga.tx --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/laliga.com/msp/tlscacerts/tlsca.laliga.com-cert.pem
CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/realmadrid.org.laliga.com/users/Admin@realmadrid.org.laliga.com/msp CORE_PEER_ADDRESS=peer0.realmadrid.org.laliga.com:7051 CORE_PEER_LOCALMSPID="RealMadridOrgMSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/realmadrid.org.laliga.com/users/Admin@realmadrid.org.laliga.com/tls/ca.crt peer channel update -o orderer.laliga.com:7050 -c $CHANNEL_NAME -f ./channel-artifacts/RealMadridOrgMSPanchors-laliga.tx --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/laliga.com/msp/tlscacerts/tlsca.laliga.com-cert.pem
CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/barcelona.org.laliga.com/users/Admin@barcelona.org.laliga.com/msp CORE_PEER_ADDRESS=peer0.barcelona.org.laliga.com:7051 CORE_PEER_LOCALMSPID="BarcelonaOrgMSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/barcelona.org.laliga.com/users/Admin@barcelona.org.laliga.com/tls/ca.crt peer channel update -o orderer.laliga.com:7050 -c $CHANNEL_NAME -f ./channel-artifacts/BarcelonaOrgMSPanchors-laliga.tx --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/laliga.com/msp/tlscacerts/tlsca.laliga.com-cert.pem
CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/atletico.org.laliga.com/users/Admin@atletico.org.laliga.com/msp CORE_PEER_ADDRESS=peer0.atletico.org.laliga.com:7051 CORE_PEER_LOCALMSPID="AtleticoOrgMSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/atletico.org.laliga.com/users/Admin@atletico.org.laliga.com/tls/ca.crt peer channel update -o orderer.laliga.com:7050 -c $CHANNEL_NAME -f ./channel-artifacts/AtleticoOrgMSPanchors-laliga.tx --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/laliga.com/msp/tlscacerts/tlsca.laliga.com-cert.pem