cd /opt/gopath/src/github.com/hyperledger/fabric/peer
export CHANNEL_NAME=channel-equipos

# Creamos el canal en base al bloque generado en configall.sh
peer channel create -o orderer.laliga.com:7050 -c $CHANNEL_NAME -f ./channel-artifacts/channel-equipos.tx --tls true --cafile  /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/laliga.com/msp/tlscacerts/tlsca.laliga.com-cert.pem
peer channel join -b channel-equipos.block

# Actualizamos el canal anadiendo cada uno de los peers
CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/barcelona.org.laliga.com/users/Admin@barcelona.org.laliga.com/msp CORE_PEER_ADDRESS=peer0.barcelona.org.laliga.com:7051 CORE_PEER_LOCALMSPID="BarcelonaOrgMSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/barcelona.org.laliga.com/users/Admin@barcelona.org.laliga.com/tls/ca.crt peer channel join -b channel-equipos.block
CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/atletico.org.laliga.com/users/Admin@atletico.org.laliga.com/msp CORE_PEER_ADDRESS=peer0.atletico.org.laliga.com:7051 CORE_PEER_LOCALMSPID="AtleticoOrgMSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/atletico.org.laliga.com/users/Admin@atletico.org.laliga.com/tls/ca.crt peer channel join -b channel-equipos.block
peer channel update -o orderer.laliga.com:7050 -c $CHANNEL_NAME -f ./channel-artifacts/LaligaOrgMSPanchors-equipos.tx --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/laliga.com/msp/tlscacerts/tlsca.laliga.com-cert.pem
CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/barcelona.org.laliga.com/users/Admin@barcelona.org.laliga.com/msp CORE_PEER_ADDRESS=peer0.barcelona.org.laliga.com:7051 CORE_PEER_LOCALMSPID="BarcelonaOrgMSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/barcelona.org.laliga.com/users/Admin@barcelona.org.laliga.com/tls/ca.crt peer channel update -o orderer.laliga.com:7050 -c $CHANNEL_NAME -f ./channel-artifacts/BarcelonaOrgMSPanchors-equipos.tx --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/laliga.com/msp/tlscacerts/tlsca.laliga.com-cert.pem
CORE_PEER_MSPCONFIGPATH=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/atletico.org.laliga.com/users/Admin@atletico.org.laliga.com/msp CORE_PEER_ADDRESS=peer0.atletico.org.laliga.com:7051 CORE_PEER_LOCALMSPID="AtleticoOrgMSP" CORE_PEER_TLS_ROOTCERT_FILE=/opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/peerOrganizations/atletico.org.laliga.com/users/Admin@atletico.org.laliga.com/tls/ca.crt peer channel update -o orderer.laliga.com:7050 -c $CHANNEL_NAME -f ./channel-artifacts/AtleticoOrgMSPanchors-equipos.tx --tls true --cafile /opt/gopath/src/github.com/hyperledger/fabric/peer/crypto/ordererOrganizations/laliga.com/msp/tlscacerts/tlsca.laliga.com-cert.pem